[package]
name="dawdle-server"
version="0.1.0"
edition="2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre="0.6.2"
env_logger="0.10.1"
log="0.4.20"
async-trait="0.1.74"

serde="1.0.193"
cuid2="0.1.2"
dashmap="5.5.3"
rand="0.8.5"
time={version="0.3.30", features=["serde"]}
argon2={version="0.5.2", features=["std"]}

futures="0.3.29"
tokio={version="1", features=["full", "macros"]}

bollard="0.15.0"
okv={version="0.3", features=["rocksdb", "rmp-serde"]}

# ssh dependencies
ed25519-dalek="2.1.0"
russh="0.40.0"
russh-keys="0.40.0"
russh-sftp="1.2.1"
axum="0.7.2"
ssh-key={version="0.6.3", features=["ed25519"]}
