[package]
name="dawdle-ssh"
version="0.1.0"
edition="2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait="0.1.74"
bollard = "0.15.0"
color-eyre="0.6.2"
dashmap = "5.5.3"
ed25519-dalek="2.1.0"
env_logger="0.10.1"
futures = "0.3.29"
log="0.4.20"
pty-process={version="0.4.0", features=["async", "tokio"]}
rand="0.8.5"
russh="0.40.0"
russh-keys="0.40.0"
russh-sftp="1.2.1"
tokio={version="1", features=["full"]}
