[fs]
user_dir="./.dawdle/users"
data_dir="./.dawdle/data"

[ssh]
port=2222
interface="127.0.0.1"

[web]
port=8008
interface="127.0.0.1"

[minecraft]
restadmin_url="https://minecraft.dawdle.space/api"
restadmin_token="password"
