# .zshrc generated by dawdle.space
export ZSH="$HOME/.config/zsh"
export ZSH_CACHE_DIR="$ZSH/cache"
export ZSH_COMPDUMP="$ZSH_CACHE_DIR/zcompdump"
export ZSH_HISTFILE="$ZSH_CACHE_DIR/history"
PROMPT="%{$fg[cyan]%}%n%{$reset_color%}@%{$fg[white]%}%m %(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ ) %{$fg[cyan]%}%c%{$reset_color%} "

export EDITOR='nano'
export BUN_INSTALL="$HOME/.bun"
export PATH="$HOME/.local/bin:$BUN_INSTALL/bin:$CARGO_HOME/bin:$PATH"
export ZSH_THEME="dawdle"
alias ls='lsd'
alias ll='ls -la'
alias la='ls -la'
alias l='ls -l'
